# Generated by Django 5.2 on 2025-06-30 14:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arabic_name', models.CharField(max_length=200, verbose_name='اسم الطالب باللغة العربية')),
                ('english_name', models.CharField(max_length=200, verbose_name='اسم الطالب باللغة الانجليزية')),
                ('religion', models.CharField(choices=[('مسلم', 'مسلم'), ('مسيحي', 'مسيحي'), ('أخرى', 'أخرى')], max_length=20, verbose_name='الديانة')),
                ('nationality', models.CharField(max_length=100, verbose_name='بلد الجنسية')),
                ('gender', models.CharField(choices=[('ذكر', 'ذكر'), ('أنثى', 'أنثى')], max_length=10, verbose_name='النوع')),
                ('governorate', models.CharField(max_length=100, verbose_name='المحافظة')),
                ('city', models.CharField(max_length=100, verbose_name='المدينة')),
                ('national_id', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='الرقم القومي يجب أن يتكون من 14 رقمًا', regex='^\\d{14}$')], verbose_name='الرقم القومي')),
                ('birthdate', models.DateField(verbose_name='تاريخ الميلاد')),
                ('mobile', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='رقم الهاتف غير صالح', regex='^\\+?\\d{10,15}$')], verbose_name='رقم الموبايل')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='البريد الالكتروني')),
                ('address', models.TextField(blank=True, verbose_name='عنوان الطالب بالتفصيل')),
                ('certificate', models.CharField(choices=[('الثانوية العامة', 'الثانوية العامة'), ('الدبلوم', 'الدبلوم'), ('معادلة', 'معادلة')], max_length=100, verbose_name='الشهادة')),
                ('institute', models.CharField(choices=[('معهد فني صحي', 'معهد فني صحي')], max_length=100, verbose_name='المعهد')),
                ('division', models.CharField(blank=True, choices=[('علوم الاشعة', 'علوم الاشعة'), ('الاجهزة الطبية', 'الاجهزة الطبية'), ('البصريات', 'البصريات'), ('الرعاية التنفسية', 'الرعاية التنفسية'), ('تركيبات اسنان', 'تركيبات اسنان'), ('المختبرات', 'المختبرات')], max_length=100, null=True, verbose_name='الشعبة')),
                ('certificate_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نسبة الشهادة')),
                ('certificate_degree', models.CharField(blank=True, max_length=50, null=True, verbose_name='مجموع الشهادة')),
                ('certificate_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2016), django.core.validators.MaxValueValidator(2024)], verbose_name='سنة الحصول على الشهادة')),
                ('preferences', models.JSONField(blank=True, default=list, help_text='في حالة عدم توفر شعبة مناسبة، يمكن إدخال أكثر من رغبة.', verbose_name='الرغبات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل')),
            ],
            options={
                'verbose_name': 'متقدم',
                'verbose_name_plural': 'المتقدمين',
                'ordering': ['-created_at'],
            },
        ),
    ]
