# Generated by Django 5.2 on 2025-07-01 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0002_applicant_application_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='application_status',
            new_name='status',
        ),
    ]
