# Generated by Django 5.2 on 2025-07-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0003_rename_application_status_applicant_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='certificate',
            field=models.CharField(max_length=100, verbose_name='الشهادة'),
        ),
    ]
