# Generated by Django 5.2 on 2025-07-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0004_alter_applicant_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='division',
            field=models.CharField(blank=True, choices=[('علوم الأشعة والتصوير الطبي', 'علوم الأشعة والتصوير الطبي'), ('المختبرات الطبية', 'المختبرات الطبية'), ('الرعاية التنفسية', 'الرعاية التنفسية'), ('صناعة تركيبات الأسنان', 'صناعة تركيبات الأسنان'), ('الأجهزة الطبية الحيوية', 'الأجهزة الطبية الحيوية'), ('البصريات', 'البصريات')], max_length=100, null=True, verbose_name='الشعبة'),
        ),
    ]
