# Generated by Django 5.2 on 2025-07-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0006_alter_applicant_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='certificate_degree',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='preferences',
        ),
        migrations.AddField(
            model_name='applicant',
            name='total_mark',
            field=models.PositiveIntegerField(default=0, verbose_name='المجموع'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='total_out_of',
            field=models.PositiveIntegerField(default=1, verbose_name='إجمالي الدرجات'),
            preserve_default=False,
        ),
    ]
