# Generated by Django 5.2 on 2025-07-06 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0007_remove_applicant_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='preference',
            field=models.CharField(blank=True, choices=[('الالتحاق بالمرحلة الأولى', 'الالتحاق بالمرحلة الأولى'), ('تركيبات الأسنان', 'تركيبات الأسنان'), ('تكنولوجيا البصريات', 'تكنولوجيا البصريات')], max_length=50, null=True, verbose_name='الرغبة'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='division',
            field=models.CharField(blank=True, choices=[('علوم الأشعة والتصوير الطبي', 'علوم الأشعة والتصوير الطبي'), ('المختبرات الطبية', 'المختبرات الطبية'), ('الرعاية التنفسية', 'الرعاية التنفسية'), ('صناعة تركيبات الأسنان', 'صناعة تركيبات الأسنان'), ('الأجهزة الطبية الحيوية', 'الأجهزة الطبية الحيوية'), ('البصريات', 'البصريات'), ('عظام', 'عظام'), ('معاون صحي / مراقب صحي', 'معاون صحي / مراقب صحي'), ('تغذية علاجية', 'تغذية علاجية'), ('صناعات دوائية', 'صناعات دوائية'), ('تسجيل طبي وإحصاء', 'تسجيل طبي وإحصاء'), ('إرشاد وتثقيف صحي', 'إرشاد وتثقيف صحي'), ('رعاية حرجة وطوارئ / تخدير ورعاية مركزية', 'رعاية حرجة وطوارئ / تخدير ورعاية مركزية')], max_length=100, null=True, verbose_name='الشعبة'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='institute',
            field=models.CharField(choices=[('معهد فني صحي حكومي', 'معهد فني صحي حكومي'), ('معهد فني صحي أزهر', 'معهد فني صحي أزهر'), ('معهد بصريات', 'معهد بصريات')], max_length=100, verbose_name='المعهد'),
        ),
    ]
