# Generated by Django 5.2 on 2025-07-06 03:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0008_applicant_preference_alter_applicant_division_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='certificate_year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2016), django.core.validators.MaxValueValidator(2025)], verbose_name='سنة الحصول على الشهادة'),
        ),
    ]
