# Generated by Django 5.2 on 2025-07-06 12:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0009_alter_applicant_certificate_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='grade',
            field=models.CharField(choices=[('جيد جدا', 'جيد جدا'), ('امتياز', 'امتياز')], default='جيد جدا', max_length=20, verbose_name='التقدير'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='institute_name',
            field=models.CharField(default='', max_length=100, verbose_name='المعهد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='mobile2',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='رقم الهاتف غير صالح', regex='^\\+?\\d{10,15}$')], verbose_name='رقم الموبايل (2)'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='division',
            field=models.CharField(blank=True, choices=[('علوم الأشعة والتصوير الطبي', 'علوم الأشعة والتصوير الطبي'), ('المختبرات الطبية', 'المختبرات الطبية'), ('الرعاية التنفسية / رعاية حرجة وطوارئ / تخدير ورعاية مركزية', 'الرعاية التنفسية / رعاية حرجة وطوارئ / تخدير ورعاية مركزية'), ('صناعة تركيبات الأسنان', 'صناعة تركيبات الأسنان'), ('الأجهزة الطبية الحيوية', 'الأجهزة الطبية الحيوية'), ('البصريات', 'البصريات'), ('عظام', 'عظام'), ('معاون صحي / مراقب صحي', 'معاون صحي / مراقب صحي'), ('تغذية علاجية', 'تغذية علاجية'), ('صناعات دوائية', 'صناعات دوائية'), ('تسجيل طبي وإحصاء', 'تسجيل طبي وإحصاء'), ('إرشاد وتثقيف صحي', 'إرشاد وتثقيف صحي')], max_length=100, null=True, verbose_name='الشعبة'),
        ),
    ]
