# Generated by Django 5.2 on 2025-07-06 15:52

import applicants.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0011_alter_applicant_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='certificate_file',
            field=models.FileField(default='', upload_to=applicants.models.certificate_file_upload_path, verbose_name='صورة واضحة من الشهادة المؤقتة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='internship_certificate',
            field=models.FileField(blank=True, null=True, upload_to=applicants.models.internship_certificate_upload_path, verbose_name='شهادة الامتياز'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='military_certificate',
            field=models.FileField(default='', upload_to=applicants.models.military_status_upload_path, verbose_name='شهادة المعاملة العسكرية'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='national_id_photo',
            field=models.FileField(default='', upload_to=applicants.models.national_id_upload_path, verbose_name='صورة بطاقة الرقم القومي'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TranscriptFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=applicants.models.transcript_upload_path, verbose_name='صورة واضحة من بيان درجات فرقة أولى وثانية')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_files', to='applicants.applicant')),
            ],
        ),
    ]
