# Generated by Django 5.2 on 2025-07-06 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0012_applicant_certificate_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='preference',
        ),
    ]
