# Generated by Django 5.2 on 2025-07-07 12:04

import applicants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0013_remove_applicant_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcriptfile',
            name='file',
            field=models.FileField(blank=True, upload_to=applicants.models.transcript_upload_path, verbose_name='صورة واضحة من بيان درجات فرقة أولى وثانية'),
        ),
    ]
