# Generated by Django 5.2 on 2025-07-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0014_alter_transcriptfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='enrollment',
            field=models.CharField(blank=True, choices=[('علوم الأشعة والتصوير الطبي', 'علوم الأشعة والتصوير الطبي'), ('المختبرات الطبية', 'المختبرات الطبية'), ('الرعاية التنفسية / رعاية حرجة وطوارئ / تخدير ورعاية مركزية', 'الرعاية التنفسية / رعاية حرجة وطوارئ / تخدير ورعاية مركزية'), ('صناعة تركيبات الأسنان', 'صناعة تركيبات الأسنان'), ('الأجهزة الطبية الحيوية', 'الأجهزة الطبية الحيوية'), ('البصريات', 'البصريات'), ('المستوى الأول', 'المستوى الأول')], max_length=100, null=True, verbose_name='الالتحاق'),
        ),
    ]
