# Generated by Django 5.2 on 2025-07-08 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0015_applicant_enrollment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicant',
            options={'ordering': ['created_at'], 'verbose_name': 'متقدم', 'verbose_name_plural': 'المتقدمين'},
        ),
    ]
