# Generated by Django 5.2 on 2025-07-14 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0016_alter_applicant_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='محل الميلاد'),
        ),
    ]
