# Generated by Django 5.2 on 2025-07-30 09:39

import applicants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0019_alter_applicant_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='military_certificate',
            field=models.FileField(blank=True, null=True, upload_to=applicants.models.military_status_upload_path, verbose_name='شهادة المعاملة العسكرية'),
        ),
    ]
