# Generated by Django 5.2 on 2025-08-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0020_alter_applicant_military_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=20, unique=True, verbose_name='الرقم القومي')),
                ('mark', models.IntegerField(blank=True, null=True, verbose_name='الدرجة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
